# Generated by Django 3.2 on 2021-10-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=250)),
                ('Last_Name', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=250)),
                ('Subject', models.CharField(max_length=500)),
                ('message_text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnquiriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=250)),
                ('Last_Name', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=250)),
                ('Subject', models.CharField(max_length=500)),
                ('message_text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Missing_personsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Location', models.CharField(max_length=250)),
                ('State_location', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=250)),
                ('Subject', models.CharField(max_length=500)),
                ('reporter_name', models.CharField(max_length=500)),
                ('Other_information', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='REALMissing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250)),
                ('missing_firstname', models.CharField(max_length=250)),
                ('missing_lastname', models.CharField(max_length=250)),
                ('missing_other_name', models.CharField(blank=True, max_length=250, null=True)),
                ('missing_AKA', models.CharField(blank=True, max_length=250, null=True)),
                ('missing_sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('missing_Age', models.CharField(max_length=240)),
                ('missing_hight', models.CharField(max_length=300)),
                ('missing_date', models.DateField()),
                ('missing_image', models.ImageField(blank=True, null=True, upload_to='missing_profile')),
                ('Last_Address', models.CharField(max_length=1000)),
                ('Last_Area', models.CharField(max_length=1000)),
                ('Last_State', models.CharField(max_length=50)),
                ('Last_city', models.CharField(max_length=50)),
                ('ContactName', models.CharField(max_length=250)),
                ('ContactPhone', models.CharField(max_length=250)),
                ('ContactEmail', models.EmailField(max_length=250)),
                ('ContactAddress', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('active', 'active'), ('found', 'found')], default='Pending', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=300)),
                ('First_name', models.CharField(max_length=300)),
                ('Last_name', models.CharField(max_length=300)),
                ('phone_number', models.IntegerField(null=True)),
                ('Date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
